### ISSUE TITLE
[CORE/SPELL] Abilities that replaces another ability

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#1005]
There is a lot of instances for this, I made this issue, so that I can refer to it in other issues, when they're related to this bug.

**Current behaviour:**

When learning an ability that replaces another, it only overrides the visual icon in your ability bar. When trying to cast your newly learned spell, you will cast the old spell.

**Expected behaviour:**

Learning a new spell that replaces another, should actually replace it.

**Steps to reproduce the problem:**

Make warrior > Take talent Impending Victory > Try to use Impending Victory > see that you can't use it because it actually tries to cast Victory Rush.

**SF rev. hash/commit:** 

Skyfire rev. 0e61f8a904c9

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
closed in: https://github.com/ProjectSkyfire/SkyFire_548/commit/9b03ba038ab822967618796cc0f58b058ffaac04
