### ISSUE TITLE
[SPELL/WARRIOR/TALENT] Impending Victory

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#1006]
This issue is related to #1005

**Current behaviour:**

When casting [Impending Victory](https://mop-shoot.tauri.hu/?spell=103840) you will get an error message. This is because it tries to cast Victory Rush, which requires you to have killed an enemy first.

**Expected behaviour:**

Impending Victory should actually replace Victory Rush.

**Steps to reproduce the problem:**

1. Make a warrior
2. Take talent Impending Victory > try to cast it on an enemy > see that you get an error saying "You can't do that yet" because it tries to cast Victory Rush.

**SF rev. hash/commit:** 

Skyfire rev. 0e61f8a904c9

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
closed in: https://github.com/ProjectSkyfire/SkyFire_548/commit/9b03ba038ab822967618796cc0f58b058ffaac04
