### ISSUE TITLE
[SPELL/WARRIOR/FURY] Wild Strike

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#1014]
**Current behaviour:**

[Wild Strike](https://mop-shoot.tauri.hu/?spell=100130) can't be cast. When trying to cast you get an error message saying "You must have a %s equipped".

**Expected behaviour:**

Should cast Wild Strike.

**Steps to reproduce the problem:**

1. Make a warrior
2. Take spec Fury > try to cast Wild Strike > see that you get an error message

**SF rev. hash/commit:** 

Skyfire rev. 0e61f8a904c9

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by lingxDEV** [comment]
Further testing shows that you can use Wild Strike with 1-handers equipped. Need to make it so you can use with 2-handers equipped too.

**Comment by AriDEV** [comment]
Description: A quick strike with your off-hand weapon that deals $m3% weapon damage plus $s2 and causes Mortal Wounds on the target.

EquippedItemClass = 2 (WEAPON)
    SubClass mask 0x0002A5F3 (AXE, AXE2, MACE, MACE2, POLEARM, SWORD, SWORD2, STAFF, FIST, DAGGER, SPEAR)
    InventoryType mask = 0x00400000 (WEAPONOFFHAND)

**Comment by AriDEV** [comment]
works as intended with onehand weapons equiped. error message also shows offhand weapon.
![grafik](https://user-images.githubusercontent.com/972273/106740738-1789f780-661b-11eb-9946-e7552665c20a.png)
![grafik](https://user-images.githubusercontent.com/972273/106740754-1b1d7e80-661b-11eb-8747-fc36b574aa02.png)
