### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by YouarexD-de** [ProjectSkyfire/SkyFire_548#1020]
**Current behaviour:**

When i complie the source i get this error and no worldserver, authserver will be build
https://gist.github.com/YouarexD-de/fa18c1f23dc8b94de42f4b68b5107b3c

**SF rev. hash/commit:** 

4ab1435277506b75d263af425e12a34bb08dca38

**Operating system:** Windows 10 x64

**Comment by AriDEV** [comment]
skyfire uses mysql 8.0 make sure to read the requirements in readme file.
