### ISSUE TITLE
Database file import

### ISSUE THREAD

**Issue by dfree686** [ProjectSkyfire/SkyFire_548#1031]
How can database file import automatically when starting the server like TrinityCore?
I don't know if it's my import problem or if the database is incomplete. When I start the server, I will be prompted that many tables are empty.

https://wiki.projectskyfire.org/index.php?title=Installation_Windows

**Comment by SkyFire** [comment]
We are not TrinityCore. An installer is included with the database download.

**Comment by dfree686** [comment]
After the database is started, manually create "auth, characters, world" and import "auth"_ database.sql  And characters_ database.sql ”, and then run "database"_ Installer_ Updater.bat ”Update the "world" library, and finally import the update file under "SQL / updates". However, after the server starts up, the, worldserver.exe It shows that many libraries are empty, and the panda novice task has not been repaired, so they can't take novice weapons or get out of the door.
![QQ截图20210226071053](https://user-images.githubusercontent.com/36804851/109231565-cf1cbe80-7801-11eb-91ea-2b3fbddebbd2.jpg)
