### ISSUE TITLE
[SPELL/MAGE/ARCANE] Arcane Charge

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#1035]
**Current behaviour:**

[Arcane Charge](http://mop-shoot.tauri.hu/?spell=36032) is _**never**_ triggered. I was able to trigger Arcane Charge once in 100 casts, not sure why it triggered that one time.

**Expected behaviour:**

Arcane Charge should be applied whenever casting Arcane Blast, Arcane Missiles and Arcane Explosion. Remember to be Arcane spec.

**Steps to reproduce the problem:**

1. Make a mage
2. Cast spec Arcane > cast Arcane Blast > see that you are not getting the Arcane Charge debuff

_Bonus bug:_
The one time I managed to proc it, I noticed some wrong calculations in the % mana cost increase, so there's something to look into there as well. Arcane Charge makes your Arcane Blast cost more mana, but the calculations made it cost so much I couldn't even cast another one.

**SF rev. hash/commit:** 

Skyfire rev. d00e2f68c50f83d36a8efce4d6ddb2ff6f644f06

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/commit/1c9bcaeee8ce87d8e98a7b9bdd2fff07e18a932f
