### ISSUE TITLE
Can't build the source on windows

### ISSUE THREAD

**Issue by dio85** [ProjectSkyfire/SkyFire_548#1041]
**Description:**
Can't build the soulution on windows, i tryed winrealwithdeb x64 build.
[https://cdn.discordapp.com/attachments/795480424393998346/853305423138652190/unknown.png](url)

**Current behaviour:**

QueryResult.cpp at line 82 give :
Error (active)	E0513	a value of type "bool *" cannot be assigned to an entity of type "my_bool *"	shared	D:\wowserverek\SkyFire_548\src\server\shared\Database\QueryResult.cpp	82
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'=': cannot convert from 'bool *' to 'my_bool *'	shared	D:\wowserverek\SkyFire_548\src\server\shared\Database\QueryResult.cpp	82	
Error (active)	E0513	a value of type "bool *" cannot be assigned to an entity of type "my_bool *"	shared	D:\wowserverek\SkyFire_548\src\server\shared\Database\QueryResult.cpp	82	
Error	LNK1104	cannot open file '..\shared\RelWithDebInfo\shared.lib'	authserver	D:\wowserverek\SkyPandaria\src\server\authserver\LINK	1	
Error	LNK1104	cannot open file '..\..\server\shared\RelWithDebInfo\shared.lib'	mmaps_generator	D:\wowserverek\SkyPandaria\src\tools\mmaps_generator\LINK	1	
Error	LNK1104	cannot open file '..\..\server\shared\RelWithDebInfo\shared.lib'	vmap4assembler	D:\wowserverek\SkyPandaria\src\tools\vmap4_assembler\LINK	1	
Error	LNK1104	cannot open file '..\shared\RelWithDebInfo\shared.lib'	worldserver	D:\wowserverek\SkyPandaria\src\server\worldserver\LINK	1	

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Build failed.

**Steps to reproduce the problem:**

1. Just try build the solution, give failed with much error.

**SF rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
For example: Skyfire rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**SFDB version:**  fresh latest

**Operating system:** WIN 10 Pro

**Comment by Crypticaz** [comment]
I'm having the same exact issue, not sure why. Did you ever find a solution @dio85

**Comment by dio85** [comment]
solved, i use 5.7.34 so need a little change 👯
