### ISSUE TITLE
Realm show offline

### ISSUE THREAD

**Issue by darksectordds** [ProjectSkyfire/SkyFire_548#1052]
Greetings to all. I apologize in advance for my poor English.

PC build machine/server:
- [X] Windows 10 21H1 19043.1110
- [X]  Visual Studio 2019 
- [X]  ACE 7.0.0
- [X]  OpenSSL 1.1.1k
- [X]  MySQL 8.0.25

The `core` was built without errors for the x64 bit version.

The databases were created with the following names:
- [X]  mop_548_auth
- [X]  mop_548_characters
- [X]  mop_548_world

The `SFDB_full_548_21.0_2021_02_07` was imported in `mop_548_world`.
The configuration files have been changed according to the database access.
[authserver.conf.txt](https://github.com/ProjectSkyfire/SkyFire_548/files/6883581/authserver.conf.txt)
[worldserver.conf.txt](https://github.com/ProjectSkyfire/SkyFire_548/files/6883582/worldserver.conf.txt)

Client was downloaded from PandaWoW.
<details><summary>uTorrent Magnet URI</summary>
<p>magnet:?xt=urn:btih:40D9F2DE25ACA3F85871139DEA2D2EA0A6B4FF34&dn=PandaWoW%205.4.8</p>
</details>

I patched the executable files through SkyFire-Community-Tools and got 4 executable files:
- PandaWoW-32.exe 
- PandaWoW-32_Patched.exe 
- PandaWoW-64.exe
- PandaWoW-64_Patched.exe 

I changed the game config so that it points to localhost.
[Config.wtf.txt](https://github.com/ProjectSkyfire/SkyFire_548/files/6883771/Config.wtf.txt)

After launching the authserver, the realm was created automatically.
![skyfire_realms](https://user-images.githubusercontent.com/11490033/127119622-2e2ba50d-5358-42d8-bca4-e077513dcd9e.png)
(except for the last one, I created it later)

**Result**: i can't enter to realm. it's always show offline after login in game.

_What I have already done:_
- i turned off the firewall completely, despite the fact that the rules allowed the authserver and the worldserver full access
- i turned off antivirus
- i changed the standard 8085 port to another one
- i registered in `worldserver. conf:: BindIP`, in the `database:: mop_548_auth:: reamlist->where (id, 1)->update(address, "IPv4")`, and in `Client/WTF/Config.wtf` that they refer not to localhost, but to IPv4
- i was adding a new realm and changing the `worldserver.conf::RealmID`

I also tried both PandaWoW executable files and patched ones after each of my attempts. 

So far, none of this has helped. There is still a possibility that the reason may be in the client itself, but with my weak Internet it is difficult to check it so quickly.

It looks as if the game client simply does not see the running `worldserver` itself, or it is listed as disabled, or not access for me (user with gm lvl 3).

**Comment by darksectordds** [comment]
**Updated**
I checked and found out that the standard ports are not occupied by other processes.

![skyfire_check_ports](https://user-images.githubusercontent.com/11490033/127131943-94006abc-beca-4fb9-9ec7-36f2adad73b3.png)

**Comment by AriDEV** [comment]
what locale is your client ?

**Comment by darksectordds** [comment]
I have
- deDE
- enGB
- esES
- frFR
- itIT
- ptBR
- ruRU

I tried to login using `ruRU` and `enGB`. On the last attempt, you can see from config.wtf that `enGB` was used.

```
SET locale "enGB"
```

**Comment by AriDEV** [comment]
are you try to connect local or remote?

**Comment by darksectordds** [comment]
Only local. I used both `127.0.0.1` and `localhost` for this, trying to avoid unpredictable errors.
I will try to use warmane client, but i will be able to download it only tomorrow because of the slow internet.

**Comment by AriDEV** [comment]
have you tried to use a diffrent wow.exe except pandawow.exe ?

**Comment by AriDEV** [comment]
a build number missmatch for a realm 18291 trying to connect with 18414 or 18414 realm trying to connect with any other build number would show as offline.
![grafik](https://user-images.githubusercontent.com/972273/127187355-c477f8b2-96de-4537-86ad-6edad67d6c80.png)

**Comment by darksectordds** [comment]
The problem is that the revision version is quite easy to check, and I set it exactly the one that is written in the game client from the bottom left.

**(PandaWoW-64.exe)**
![skyfire_clien_rev](https://user-images.githubusercontent.com/11490033/127189262-80e00f28-ca15-4f13-b224-429945ae2c37.png)

I changed the localization in `worldserver.conf` to English (`RealmZone = 8`) so far without results.

![skyfire_local_enGB](https://user-images.githubusercontent.com/11490033/127189708-4547bd41-317b-488f-aa5e-8a6498191dfa.png)

**Comment by AriDEV** [comment]
are you in our discord if so what is your name ?

**Comment by darksectordds** [comment]
My internet is so bad that I can't even sit in a chat. In the evening (and I have an evening now), the ping can reach 10 seconds on 4g. Here is such a large load on the 4g tower in the town.

I will try to download the client from warman tomorrow. It looks cleaner. And tomorrow I'll see if anything has changed or not.

**Comment by darksectordds** [comment]
I wanted to download only one executable file, but I had to download the entire client completely, because there are bugs in uTorrent and if you skip files, it still downloads them.

However, when I downloaded it, set the standard settings to localhost, everything started immediately. In other words, the reason was precisely in the client (executable file).

![skyfire_client_from_warmane](https://user-images.githubusercontent.com/11490033/127272491-6e5d23c6-1da8-49c5-8357-2c1e34d918c9.png)

**Comment by darksectordds** [comment]
Simple offtop: 
Are such problems still commonplace? Or am I the only one who has them?

```
No defined handler for opcode [UNKNOWN OPCODE 0x6F5 (1781)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1F9E (8094)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x44E (1102)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x365 (869)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x32D (813)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x813 (2067)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0xA23 (2595)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [CMSG_VOICE_SESSION_ENABLE 0x15A9 (5545)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [CMSG_GUILD_SET_ACHIEVEMENT_TRACKING 0xCF0 (3312)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [UNKNOWN OPCODE 0x1203 (4611)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [CMSG_SAVE_CUF_PROFILES 0x6E6 (1766)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [CMSG_NEXT_CINEMATIC_CAMERA 0x1124 (4388)] sent by [Player: Jora (Guid: 3, Account: 1)]
Disabled opcode [UNKNOWN OPCODE 0x27D (637)] have opcode value, but is disabled missing structure update?
No defined handler for opcode [CMSG_COMPLETE_CINEMATIC 0x1F34 (7988)] sent by [Player: Jora (Guid: 3, Account: 1)]
No defined handler for opcode [CMSG_QUEST_NPC_QUERY 0x1DAE (7598)] sent by [Player: Jora (Guid: 3, Account: 1)]
```

**Comment by AriDEV** [comment]
those are messages that we print to the console when we recv an not yet implemented packet/not updated packet.

**Comment by darksectordds** [comment]
Do you need same help with modify core/sql? I played MoP and remember a lot of things as they should really be. Perhaps I will play on my local server and sometimes fix some errors.

I have made a fork and will make a pull request if I change something. And then you can decide for yourself whether you need it or not.

**Comment by AriDEV** [comment]
Usualy in open source projects every one is welcome to share their issues/code with the community if they want to.

**Comment by darksectordds** [comment]
> are you in our discord if so what is your name ?

Still, you can not do without direct communication here, because it is not clear in which direction you are going to develop the project. I can make edits and the gameplay will be like in the original MoP, but it's not a fact that the database itself will be saved in the form in which you expect (like Blizz like).

My name is Stas and here is my discord: `zdohdds#6222`.
It is necessary to determine all the nuances.

**Comment by AriDEV** [comment]
https://discord.gg/DnKZycD
