### ISSUE TITLE
Items avoid player backpack

### ISSUE THREAD

**Issue by darksectordds** [ProjectSkyfire/SkyFire_548#1065]
Despite the fact that I have additional bags besides the main one, the items are not moved to additional bags, but to the bank.
PS: sorry for bad English.

**My loot log:**
![player](https://user-images.githubusercontent.com/11490033/128498043-e019c215-a4e5-41ab-bae3-352a554c6105.png)

**Bank:**
![bank](https://user-images.githubusercontent.com/11490033/128498085-b014193c-755e-4a10-b4f0-a1e2a6e71f14.png)

**Comment by AriDEV** [comment]
can you disable bagnon and try with normal blizz bags if the issue is the same ?

**Comment by darksectordds** [comment]
Take a look example with **[Minor Healing Potion] = 118**.

If I check the  `characters`.`character_inventory` table,  I will not find there a record with the `item` = 118, but i can find it in `characters`.`item_instance`.

**Comment by darksectordds** [comment]
In subsequent tests, it turned out that filling the cells of the bags has an unpredictable behavior.
The following image shows that the first loot go out to the bank, and the next one went to the bags.

![unk](https://user-images.githubusercontent.com/11490033/128502606-9f8b31b3-398d-4295-b121-b1ca420bf072.png)

**Comment by AriDEV** [comment]
![grafik](https://user-images.githubusercontent.com/972273/128512596-52c762a3-2efb-46b6-9beb-b6e07f7905b8.png)
im unable to reproduce this i loot 4 i have 4 in bag

**Comment by Crypticaz** [comment]
I think bagnon has issues with the client atm. I was using it but caused too many problems so I disabled it

**Comment by darksectordds** [comment]
> I think bagnon has issues with the client atm. I was using it but caused too many problems so I disabled it

A little higher, I proved that it's not an addon. I don't understand why you are so fixated on this.
The problem is precisely in creating new item records when the main bag is already full.

**Comment by Crypticaz** [comment]
> > I think bagnon has issues with the client atm. I was using it but caused too many problems so I disabled it
> 
> A little higher, I proved that it's not an addon. I don't understand why you are so fixated on this.
> The problem is precisely in creating new item records when the main bag is already full.

Because bagnon has issues 🙄 but it seems like it's not the addon. I'll try and confirm later on if I have time

**Comment by darksectordds** [comment]
> Because bagnon has issues 🙄 but it seems like it's not the addon. I'll try and confirm later on if I have time

Does Bagnon have direct access to the database bypassing the server? Is Bagnon interfering in the American elections?: D

Aside from the joke. The answer is no. 
When moving an item, a request is formed, which is packaged on the client side and transmitted to the server. On the server side, the server unpacks the package and checks the data for validity. And only then forms the logic of what to do with this data.

And somewhere on the server side there is an error that creates a general record about the subject in `characters`.`item_instance`, but does not create an entry in `characters`.`character_inventory`. That is why the tem is moved to the bank, and not to the bag.

**Comment by Crypticaz** [comment]
> > Because bagnon has issues 🙄 but it seems like it's not the addon. I'll try and confirm later on if I have time
> 
> Does Bagnon have direct access to the database bypassing the server? Is Bagnon interfering in the American elections? ;D
> 
> Aside from the joke. The answer is no.
> When moving an item, a request is formed, which is packaged on the client side and transmitted to the server. On the server side, the server unpacks the package and checks the data for validity. And only then forms the logic of what to do with this data.
> 
> And somewhere on the server side there is an error that creates a general record about the subject in `characters`.`item_instance`, but does not create an entry in `characters`.`character_inventory`. That is why the item is moved to the bank, and not to the bag.

Can you write the exact steps to reproduce the issue?

**Comment by darksectordds** [comment]
By pressing the right button on the item in the bank, he transfers it back to the bank, but to another cell, instead of transferring this item to the bags.

![unk_1](https://user-images.githubusercontent.com/11490033/128595507-c6587739-9bd1-4a67-a600-fea14398597e.png)

**Comment by darksectordds** [comment]
> Can you write the exact steps to reproduce the issue?

You need to have from right to left next bags:
1. Fatcandle Bag (4 slot)
2. Small Red Pouch (6 slot)
3. Small Blue Pouch (6 slot)
4. Grape-Picking Sack (6 slot)

And play the game move then 10 min.
I did the quest [Kobold Candles] when got the issue.

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/commit/2cccdb316560a0f4e75f7e8936ed38fc0625c62c

**Comment by darksectordds** [comment]
The commit above fixed issue.
