### ISSUE TITLE
Items in mail after character boost are unclaimable

### ISSUE THREAD

**Issue by cthu1hoo** [ProjectSkyfire/SkyFire_548#1066]
Items in mail (i.e. embersilk bags, etc.) received in mail after character boost cannot be claimed (error reported "This item doesn't belong to you").

This causes persistent new mail  icon in the UI because this mail message cannot be deleted (because it has unclaimable items) or returned.

Steps to reproduce:

- Create new character (level 1)
- Use character boost on the character
- Login to MoP shrine, pending mail message cannot be claimed

Using trunk branch, latest as of yesterday. Latest database off the forums.

Somewhat unrelated, but which branch is more complete - main or trunk? It seems that both branches are being developed on.

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/commit/44849b26b2a529b974fd94e406986df870020f9b
