### ISSUE TITLE
Quest: incomplete mark

### ISSUE THREAD

**Issue by darksectordds** [ProjectSkyfire/SkyFire_548#1068]
In the very initial starting zone for people, there are many quests that are marked as incomplete, although they can be passed.
The first quest is `quest=28786 (Join The Battle | for priest)` it is not marked as completed, although you just need to pass it.

Maybe I'm wrong, but no one of the `server/game/Handlers/QuestHenlder.cpp` functions that I couldn't intercept any that could change the status of the quest.

Maybe it is necessary to use unused features, like an unarilized `CMSG_QUEST_NPC_QUERY`?

aef33ebba622370f8298cf3858d6f75bad6fe701

**Comment by AriDEV** [comment]
the quest does not have a quest objective and is not flagged as autocomplete

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/commit/08f7c3cdb908b924272d0251e5fb3b12c23e5706

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/commit/691f570c724a11bd63aced4d3b389a86951d7182

**Comment by darksectordds** [comment]
> [691f570](https://github.com/ProjectSkyfire/SkyFire_548/commit/691f570c724a11bd63aced4d3b389a86951d7182)

You rushed to close the issue too soon.
Because there are many similar issues with quests, but different solutions.

The second quest is `The Fargodeep Mine (quest=62)` that has some issue, but he must change the quest mark after the area is explored. The area is being explored, the quest is counted, but the quest mark does not change.

**PS:** When I had free time, I played with flags on the `quest=28786 (Join The Battle | for priest)` and apparently, they are not determined correctly which can also be one of the problems. 
Example: flag was 135069696 by default

```
-- was flag = 135069696 != 851968
-- 1000 0000 1101 0000 0000 0000 0000 (135069696 dec) 1 bit = 134217728(QUEST_FLAGS_PORTRAIT_FROM_LOG)
-- 0000 0000 1101 0000 0000 0000 0000 (851968 dec)

851968 = 524288(QUEST_FLAGS_AUTO_ACCEPT) & 262144(QUEST_FLAGS_OBJ_TEXT) & 65536(QUEST_FLAGS_AUTOCOMPLETE)

If we remove the highest bit = QUEST_FLAGS_PORTRAIT_FROM_LOG, then flag will be 851968, which should give a similar result, but we will get that the quest will be considered as completed daily.

Which is very strange and suggests a mess with these flags in the quest system.
```

**Comment by AriDEV** [comment]
quest 62 does have a quest objective in db 252033 for type 10
