### ISSUE TITLE
Creature: Mana Wyrm

### ISSUE THREAD

**Issue by YukkiKun** [ProjectSkyfire/SkyFire_548#1074]
**Description:**

You can't kill the Mana Wyrm and progress further.

**Current behaviour:**

You can't kill the creature.

**Expected behaviour:**

You should be able to kill it.

**Steps to reproduce the problem:**

1. Create a blood elf or go to blood elves start zone
2. Find a Mana Wyrm ( ID: 15274 )
3. Try to attack it.

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win64, Release) (worldserver-daemon)

**SFDB version:**   548-21.0

**Operating system:** Windows 7 x64

**Comment by AriDEV** [comment]
![grafik](https://user-images.githubusercontent.com/972273/129217484-847af968-959b-4ed1-a809-6a0a78af4377.png)

**Comment by AriDEV** [comment]
![grafik](https://user-images.githubusercontent.com/972273/129217558-2e8337c1-62f5-45ff-9de1-1348c9a4400a.png)

**Comment by AriDEV** [comment]
![grafik](https://user-images.githubusercontent.com/972273/129217893-87ee42e5-a188-48aa-892f-02166965b9b8.png)
