### ISSUE TITLE
Mission Bug 

### ISSUE THREAD

**Issue by pomocnik-mma** [ProjectSkyfire/SkyFire_548#1078]
**Description:**

In mission Thunderhorn Cleansing if i use the "Thunderhorn Cleansing Totem" i see on the screen "Requires %s"

**Comment by AriDEV** [comment]
![grafik](https://user-images.githubusercontent.com/972273/129409830-cc12e9d0-1a18-4e19-a056-d91adf5dd703.png)
you need to stand on top of the well

**Comment by Err0r1** [comment]
> ![grafik](https://user-images.githubusercontent.com/972273/129409830-cc12e9d0-1a18-4e19-a056-d91adf5dd703.png)
> you need to stand on top of the water well

https://youtu.be/iaLCQhU4k0Y?t=90

It's not blizzlike :)

**Comment by pomocnik-mma** [comment]
Ok thanks

**Comment by AriDEV** [comment]
@Err0r1 you linked a video to the pre cataclysm version of the quest. after cata the npcs around are diffrent and yes i agree i think the data1 in the spell focus must be higher then what we currently have

**Comment by pedrobz2** [comment]
Bugged!

![image](https://user-images.githubusercontent.com/89158263/129951252-239a11ab-f8ac-49e1-9c7d-658c3bd5d40c.png)

**Comment by Err0r1** [comment]
> Bugged!
> 
> ![image](https://user-images.githubusercontent.com/89158263/129951252-239a11ab-f8ac-49e1-9c7d-658c3bd5d40c.png)

Wrong issue, make a new one!

- close request
