### ISSUE TITLE
update 2021_02_05_00_characters.sql to character database failed

### ISSUE THREAD

**Issue by anondatura** [ProjectSkyfire/SkyFire_548#1087]
**Description:**

Updating last update 2021_02_05_00_characters.sql to character database not working properly

**Current behaviour:**
`mysql -uroot -p characters < 2021_02_05_00_characters.sql

ERROR 1060 (42S21) at line 1: Duplicate column name 'PetSpecId'`

**Expected behaviour:**

Updating without failing.

**Steps to reproduce the problem:**

1. Creating clean database in mysql : CREATE DATABASE `characters` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
2. Grant access in mysql :  GRANT ALL PRIVILEGES ON `characters` . * TO 'skyfire'@'localhost' WITH GRANT OPTION;
3. Applied base character. characters_database.sql to character database : success
3. Applied 2019_05_04_01.sql to character database : success
4. Applied 2020_03_09_00_characters.sql : success

**SF rev. hash/commit:** 
SkyFire 5.x.x rev. 2bcfa6e1f539 2021-09-05 17:12:54 +0200 (trunk branch) (Unix, Release) (authserver)
SkyFire 5.x.x rev. 2bcfa6e1f539 2021-09-05 17:12:54 +0200 (trunk branch) (Unix, Release) (worldserver-daemon)

**SFDB version:**  SFDB_full_548.21.0_2021_02_07 Version of the Skyfire database

**Operating system:** 
`
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

NAME="Debian GNU/Linux"

VERSION_ID="11"

VERSION="11 (bullseye)"

VERSION_CODENAME=bullseye
`
`
mysql  Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL)
`

**Comment by SkyFire** [comment]
You don't need to apply any character table updates if you are starting fresh.
