### ISSUE TITLE
Crash world 2bcfa6e1f539 : Unknown column 'quantity' in 'field list'

### ISSUE THREAD

**Issue by anondatura** [ProjectSkyfire/SkyFire_548#1088]
**Description:**

worldserver not working

**Current behaviour:**

https://gist.github.com/anondatura/3135376a350cdf282a9de75b944558a7

**Expected behaviour:**

Worldserver not crashing

**Steps to reproduce the problem:**

1. clone last branch
2. build worldserver, auth...
3. update auth, characters, world database
4. run worldserver

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. 2bcfa6e1f539 2021-09-05 17:12:54 +0200 (trunk branch) (Unix, Release) (worldserver-daemon

**SFDB version:**  SFDB_full_548.21.0_2021_02_07 Version of the Skyfire database

**Operating system:**

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

NAME="Debian GNU/Linux"

VERSION_ID="11"

VERSION="11 (bullseye)"

VERSION_CODENAME=bullseye

mysql Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by kuramajssken001** [comment]
DROP TABLE IF EXISTS `character_currency`;
CREATE TABLE `character_currency` (
  `guid` int unsigned NOT NULL,
  `currency` smallint unsigned NOT NULL,
  `total_count` int unsigned NOT NULL,
  `week_count` int unsigned NOT NULL,
  `season_count` int unsigned NOT NULL,
  `flags` int unsigned NOT NULL,
  PRIMARY KEY (`guid`,`currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

run sql

**Comment by anondatura** [comment]
Thank you for your reply.

I change my character database with this (quantity, weekly_quantity, tracked quantity were missing).
It works.

Problem solved.

DROP TABLE IF EXISTS `character_currency`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `character_currency` (
  `guid` int(10) unsigned NOT NULL,
  `currency` smallint(5) unsigned NOT NULL,
  `total_count` int(10) unsigned NOT NULL,
  `week_count` int(10) unsigned NOT NULL,
  `season_count` int(10) unsigned NOT NULL,
  `flags` int(5) unsigned NOT NULL,
  `quantity` int(5) unsigned NOT NULL,
  `weekly_quantity` int(5) unsigned NOT NULL,
  `tracked_quantity` int(5) unsigned NOT NULL,
  PRIMARY KEY (`guid`,`currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
