### ISSUE TITLE
The client can not create a new character. Client stuck at creation character.

### ISSUE THREAD

**Issue by anondatura** [ProjectSkyfire/SkyFire_548#1089]
**Description:**

The client can not create a new character

**Current behaviour:**

The client is blocked in a loop when I try to create a new character.
The character is not created, and the client goes back to the creation character again.

Hereafter the worldserver log :
https://gist.github.com/anondatura/cbbf5841203782abab64203c62339d52

**Expected behaviour:**

Create a character and play with it.

**Steps to reproduce the problem:**

1. Clean installation
2. Connect to authserver with client
3. try to create a character

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. 2bcfa6e1f539 2021-09-05 17:12:54 +0200 (trunk branch) (Unix, Release) (worldserver-daemon)

**SFDB version:**  SFDB_full_548.21.0_2021_02_07 Version of the Skyfire database

**Operating system:** CHANGEME OS

RETTY_NAME="Debian GNU/Linux 11 (bullseye)"

NAME="Debian GNU/Linux"

VERSION_ID="11"

VERSION="11 (bullseye)"

VERSION_CODENAME=bullseye

mysql Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by kuramajssken001** [comment]
Please import the complete characters database.

**Comment by nygula** [comment]
table realmlist
