### ISSUE TITLE
Compilation error in UBUNTU 20.04

### ISSUE THREAD

**Issue by Tommy-Traviline** [ProjectSkyfire/SkyFire_548#1108]
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: note: use -Winvalid-pch for more information
<command-line>: fatal error: /home/cloud/build/src/server/shared/sharedPCH.h: No such file or directory
compilation terminated.
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/build.make:63: src/server/shared/CMakeFiles/shared.dir/Configuration/Config.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:680: src/server/shared/CMakeFiles/shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Built target generate_ScriptPCH.cpp
make: *** [Makefile:130: all] Error 2

**Comment by htc16** [comment]
I'm having the same problem!

**Comment by SkyFire** [comment]
What branch?

**Comment by htc16** [comment]
> What branch?

The main
