### ISSUE TITLE
Patcher skyfire

### ISSUE THREAD

**Issue by Linogreco** [ProjectSkyfire/SkyFire_548#1110]
**Description:**

The patcher doesn't work on 5.4.8

**Current behaviour:**

The patcher in the folder 5.4.8 do not open and the patch in 4.0 folder, that is the skyfirepatcher says that "cannot find a wow .exe"

**Expected behaviour:**

Patch works. 

**Steps to reproduce the problem:**

1. Copy the patch to wow folder and run

**SF rev. hash/commit:** 

CHANGEME Copy the first line of the `worldserver`, `authserver` or `bnetserver` startup.
For example: Skyfire rev. 0000000000 2000-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (bnetserver)

**SFDB version:**  22

**Operating system:** Windows 10 64.

**Comment by SkyFire** [comment]
If the client is already patched it will not find the client.
