### ISSUE TITLE
CMAKE Broken :D

### ISSUE THREAD

**Issue by JustZerooo** [ProjectSkyfire/SkyFire_548#1115]
CMake Warning (dev) at CMakeLists.txt:7 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Setting build type to 'Release' as none was specified.
Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled generic compiletime warnings
MSVC: C++20 Standard Enabled.
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL (missing: OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/macros/FindOpenSSL.cmake:184 (find_package_handle_standard_args)
  CMakeLists.txt:56 (find_package)

Configuring incomplete, errors occurred!

**Comment by Nightprince** [comment]
Install OpenSSL 1.1.1

**Comment by JustZerooo** [comment]
super comment, it is already installed but not on c: it is on d:

**Comment by Nightprince** [comment]
> super comment, it is already installed but not on c: it is on d:

So, in advance mode, enter the path.

**Comment by leewheel** [comment]
CMake Error: The source "D:/3.548Project/SkyFire/1.Source/20231023/SkyFire_548/CMakeLists.txt" does not match the source "D:/3.548Project/SkyFire/1.Source/20231019/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

**Comment by AriDEV3** [comment]
delete cmake cache and generate aggain.

**Comment by SkyFire** [comment]
Build works just fine if all requirements are met. Please see the readme for the latest dependency info.
