### ISSUE TITLE
worldserver Crashes

### ISSUE THREAD

**Issue by md5xwl** [ProjectSkyfire/SkyFire_548#1116]
win10, mysql 8.0.34.
All work on this page has been completed. http://wiki.projectskyfire.org/index.php?title=Installation_Windows.
when I login in and double click the server, worldserver Crashes.  NO common logs.

I uploaded the file in Crashes floder.
[unknown_worldserver.exe_[13-9_16-13-53].txt](https://github.com/ProjectSkyfire/SkyFire_548/files/12595180/unknown_worldserver.exe_.13-9_16-13-53.txt)

and server.log
[Server.log](https://github.com/ProjectSkyfire/SkyFire_548/files/12595196/Server.log)

and DBerrors
[DBErrors.log](https://github.com/ProjectSkyfire/SkyFire_548/files/12595200/DBErrors.log)

**Comment by md5xwl** [comment]
The client  is 5.4.8 18184 Zh-CN

**Comment by Snify89** [comment]
You have Windows 8 according to the log.
You need reinstall/update OpenSSL (3)

**Comment by md5xwl** [comment]
> You have Windows 8 according to the log. You need reinstall/update OpenSSL (3)
My os is win10 22H2
The SSL's version is 3.1.2。

**Comment by md5xwl** [comment]
> You have Windows 8 according to the log. You need reinstall/update OpenSSL (3)

My os is win10 22H2
The SSL's version is 3.1.2。

**Comment by Snify89** [comment]
> > You have Windows 8 according to the log. You need reinstall/update OpenSSL (3)
> 
> My os is win10 22H2 The SSL's version is 3.1.2。

In the log file it says Windows 8.
Maybe the OS detection for Windows 10 is not yet implemented.
Anyway. 
The error states an ACCESS_VIOLATION in the ReadFile API.
Maybe try running worldserver as Administrator or install OpenSSL to another (user) Path.

**Comment by md5xwl** [comment]
After reinstalling OpenSSL version 1.1.1 instead of 3.x, I was able to log into the game normally.
Thank you。
