### ISSUE TITLE
SQL details pn instructions guide needs updating

### ISSUE THREAD

**Issue by RavingSmurfGB** [ProjectSkyfire/SkyFire_548#1157]
**Description:**

In step 3.1 (Importing World Database) the instructions tell you to go to your forum and download the database, the link given for which loads your forum and is blank.

Link to website:
- https://wiki.projectskyfire.org/index.php/Installation_(Windows_5xx)#Importing_World_Database

**Expected behaviour:**

Update the link to:
https://github.com/ProjectSkyfire/SkyFire_548/releases/tag/548-21.0

Update the text to:
Grab the latest version of SkyFireDB_5xx from our github releases

**Comment by SkyFire** [comment]
Updated
