### ISSUE TITLE
Database_Installer_Updater.bat fails 

### ISSUE THREAD

**Issue by RavingSmurfGB** [ProjectSkyfire/SkyFire_548#1158]
**Description:**

Database_Installer_Updater.bat errors and does not install world database

**Current behaviour:**

Downloading the database release from:
- https://github.com/ProjectSkyfire/SkyFire_548/releases/tag/548-21.0

I run the Database_Installer_Updater.bat file (after extracting everything)
Enter the IP address, credentials and inform it of the World database. (which I have created as per the instructions https://wiki.projectskyfire.org/index.php/Installation_(Windows_5xx)#IMPORTING_THE_DATABASE)
I then press 1 , which is (1 - Install 5.4.8 World Database and all updates, NOTE! Whole db will be overwritten!)

However I recieve a mysql.exe System Error
- it states:
```
The code execution cannot proceed because libssl-1_1-x64.dll was not found. Reinstalling the program may fix this program
```
![image](https://github.com/ProjectSkyfire/SkyFire_548/assets/23278939/de559acf-1dd3-4a76-9cb7-aae9b1aaff3e)

- Pressing okay, then provides another error
```
The code execution cannot proceed because libcrypto-1_1-x64.dll was not found. Reinstalling the program may fix this program
```

![image](https://github.com/ProjectSkyfire/SkyFire_548/assets/23278939/27c2cb31-e733-4d98-a92a-9aad19bc6e45)

This continous for every mysql operation, accepting each error leads to the script believing all operations have been succesful
![image](https://github.com/ProjectSkyfire/SkyFire_548/assets/23278939/3ad96086-4551-4eab-9e0b-b0b9dd92e92f)

I believe this bat file is using the included mysql.exe in the dep folder, which means this should be included i think.

I am able to connect to my database using the same credentials.

**Expected behaviour:**

For the Database_Installer_Updater.bat to install the world database

**SFDB version:**  548-21.0
**MYSQL version** 5.7.26
**Operating system:** Windows 10 Build 19045

Thanks for any help in advance, I am soo confused!

**Comment by SkyFire** [comment]
Database releases were moved. It all works here
https://github.com/ProjectSkyfire/database/releases/tag/R23.000

**Comment by RavingSmurfGB** [comment]
Ah okay, thanks for linking that but I still recieve the same error
![image](https://github.com/ProjectSkyfire/SkyFire_548/assets/23278939/5475e5df-1d7d-4071-8b84-0a083087a845)

**Comment by RavingSmurfGB** [comment]
okay, but do you know how to get around that, it seems that the mysql quries arent executing due to this, 

are you able to reproduce the problem?

**Comment by AriDEV3** [comment]
lib crypto is an openssl lib maybe reinstalling openssl

**Comment by RavingSmurfGB** [comment]
Can do, I have 32bit openssl 1.1.1w installed

I have just uninstalled, reinstalled and restarted my pc but I still get te same errors

**Comment by AriDEV3** [comment]
you should use 64bit

**Comment by RavingSmurfGB** [comment]
Yep that seem to do the trick, thanks so much @AriDEV3 !!

I had the 32bit openssl installed as I was trying to compile the server, and 64bit compilation seemed trickier
 - this was before I saw a release with the server pre-compiled :p
