### ISSUE TITLE
extracter.exe missing from Development build (latest release)

### ISSUE THREAD

**Issue by RavingSmurfGB** [ProjectSkyfire/SkyFire_548#1159]
**Description:**

I am attempting to generate the DBC, MAPS, VMAPS and MMAPS according to the install instructions:
- https://wiki.projectskyfire.org/index.php/Installation_(Windows_5xx)#DBC,_MAPS,_VMAPS,_and_MMAPS

It explains I am meant to have the following files to copy to my wow client:
- extractor.exe 
- vmap3extractor.exe
- vmap3assembler.exe
- ace.dll
- Simple_Extractor.bat
-mmaps_generator.exe

However the following are not there:
- extractor.exe
- vmap3extractor.exe (vmap4 is included which i guess I use instead)
- vmap3assembler.exe (vmap4 is included which i guess I use instead)
- Simple_Extractor.bat

Without these files DBC and MAPS will not be extracted and the server will not run.

I was also hoping to clarify since the wiki says I need a fully patched 4.0.6a client, would this be done via the 5.4.8 (18414) client, otherwise pandaria maps would not be availible to extract.

Again thank you for the help provided so far, I really appreciate it!

**Current behaviour:**

**Expected behaviour:**

Those files to be there or the instructions on the wiki to be modified

**Steps to reproduce the problem:**

Download the Development Build(2023-01-16) 
- https://github.com/ProjectSkyfire/SkyFire_548/releases/tag/latest
Then navigate to RelWithDebInfo to view the missing files

**Comment by RavingSmurfGB** [comment]
Ah okay, I think I got confused about the extractors with the latest developmental release which are missing those files.
But i discovered the extracters in the SkyFire-Community-Tools, which seem to have everything :)
- https://github.com/ProjectSkyfire/SkyFire-Community-Tools/tree/master/Extractors/548



Would it be possible to change the wording of the wiki, for the following things
From
```
The VERY FIRST THING you need is a WoW client fully patched to version 4.0.6a (build 13623) 
```
To
```
The VERY FIRST THING you need is a WoW client fully patched to version 5.4.8 (build 18414), view the Connection Patcher.exe on the SkyFire-Community-Tools repository for this file:
https://github.com/ProjectSkyfire/SkyFire-Community-Tools/tree/master/SkyFire%20Patcher/548
```
I am also not sure if there is a  config.wtf AND launcher.wtf for this client, so perhaps changing the wording to make that a litttle clearer.


And then to clear up which extractors you use when downloaded a pre-compiled release, you could put something like:
```
If you have downloaded a pre-compiled version of skyfire, the extractors are availible under the SkyFire-Community-Tools repository located:
- https://github.com/ProjectSkyfire/SkyFire-Community-Tools/tree/master
```
It also might be worth mentioning somewhere if that developmental release is 32bit or 64bit so it is known which bit to use when extracting.

Again thanks for the awesome work you do!

**Comment by SkyFire** [comment]
We are not supporting any of those older pre-releases. Better off just compiling everything from scratch.

**Comment by RavingSmurfGB** [comment]
ah okay, I didnt see the date on it to be honest :P

Will give it a go :)
