### ISSUE TITLE
Compilation error SkyFire requires version 19.30.30423.0 (MSVC 2022) to build but found 19.29.30152.0

### ISSUE THREAD

**Issue by RavingSmurfGB** [ProjectSkyfire/SkyFire_548#1161]
**Description:**
  
  I am attempting to compile skyfire using visual studio 2019 as per the install instructions, however it fails and informs me it needs MSVC 2022

**Current behaviour:**
  
  Upon attempting the compilation, the following error is given.
![image](https://github.com/ProjectSkyfire/SkyFire_548/assets/23278939/fc95c976-4a8c-42c9-b741-34401ef04bdb)

**Expected behaviour:**

  For the compliation process to use visual studio 2019 as per the install instructions:
  - https://wiki.projectskyfire.org/index.php/Installation_(Windows_5xx)#Software_Required

**Steps to reproduce the problem:**
  
  Software Used:
  - cmake-3.28.0-rc3-windows 64bit
  - openssl-1.1.1w 64bit (not light)
  - Visual Studio Community 2019 version 16.11 x86
  
  1. I downloaded Visual Studio Community 2019 version 16.11 x86  from the following link (https://my.visualstudio.com/Downloads?q=visual%20studio%202019&wt.mc_id=o~msft~vscom~older-downloads)
  2. When installing I select Desktop development with c++ to be installed
  3. I pull the latest repository via:
  - git clone -b trunk https://github.com/ProjectSkyfire/SkyFire_548.git
  4. I load up cmake and open the source code I just pulled
  - C:\Users\joe\Documents\WoW MoP\development\before compilation\SkyFire_548
  5. I set the build directory to be
  - C:\Users\joe\Documents\WoW MoP\development\before compilation\build
  6. I click configure and set the generator to be Visual Studio 16 2019 (Use default native compilers)
  7. However I recieve an error informing me that SkyFire requires version 19.30.30423.0 (MSVC 2022) to build but found
    19.29.30152.0
full log output
```
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
The C compiler identification is MSVC 19.29.30152.0
The CXX compiler identification is MSVC 19.29.30152.0
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Setting build type to 'Release' as none was specified.
Detected 64-bit platform
CMake Error at cmake/compiler/msvc/settings.cmake:13 (message):
  MSVC: SkyFire requires version 19.30.30423.0 (MSVC 2022) to build but found
  19.29.30152.0
Call Stack (most recent call first):
  cmake/platform/win/settings.cmake:36 (include)
  cmake/macros/CheckPlatform.cmake:18 (include)
  CMakeLists.txt:49 (include)


Configuring incomplete, errors occurred!
```

**SF rev. hash/commit:** commit c2cbd0f

**Operating system:** Windows 10 Build 19045

**Comment by RavingSmurfGB** [comment]
My question is, should a different version of visual studio be used?

**Comment by AriDEV3** [comment]
yes skyfire requires visual studio 2022

**Comment by RavingSmurfGB** [comment]
Ah okay, would you be able to update the instructions on the wiki to reflect that 
- https://wiki.projectskyfire.org/index.php/Installation_(Windows_5xx)#DBC,_MAPS,_VMAPS,_and_MMAPS

The line is:
2. Install the compiler Visual C++ 2019 Community
