### ISSUE TITLE
Many errors occurred after installing the database

### ISSUE THREAD

**Issue by TS-BAH** [ProjectSkyfire/SkyFire_548#1182]
**Description:**

There are too many database errors. Are my installation steps wrong?
[DBErrors.log](https://github.com/ProjectSkyfire/SkyFire_548/files/13218538/DBErrors.log)

**Steps to reproduce the problem:**

1: Create 3 databases
2: Install the "SFDB_full_548_22.000_2023_10_19_Release" database
3:Apply updates under "updates\world"

SkyFire 5.x.x rev. 567b4b28de24+ 2023-10-29 10:34:32 -0500 (main branch) (Win64, RelWithDebInfo) (worldserver-daemon)

**SFDB version:**  Using World DB: SFDB 548.Release.23.000

**Operating system:** Windows 10 Build  19045.3570

**Comment by SkyFire** [comment]
It's just incomplete data. We don't need an error report for this. This is a known issue.
