### ISSUE TITLE
Cant stop /dance

### ISSUE THREAD

**Issue by Luzifix** [ProjectSkyfire/SkyFire_548#702]
Hello,

if you start LOOP emotes like /dance you cant stop it.

**Comment by SkyFire** [comment]
Time to boogie. I just can't stop dancing. Confirmed.

**Comment by Luzifix** [comment]
Can you say me the packet, i can try to fix it

**Comment by soulfrost** [comment]
@Luzifix smsg_emote

**Comment by Goatform** [comment]
```
        [Parser(Opcode.SMSG_EMOTE)]
        public static void HandleEmote(Packet packet)
        {
            var emote = packet.ReadInt32E<EmoteType>("Emote ID");
            var guid = packet.ReadGuid("GUID");

            if (guid.GetObjectType() == ObjectType.Unit)
                Storage.Emotes.Add(guid, emote, packet.TimeSpan);
        }
```

**Comment by AriDEV** [comment]
0x0987 || 2439 || 007AD97C || 295 || SMSG_LEGACY_EMOTE

**Comment by Luzifix** [comment]
i switch to trinity 6.x but thx for your answer :+1:

**Comment by AriDEV** [comment]
@Luzifix i dont really care

**Comment by alterego21** [comment]
Roflmao. Tc pffft

**Comment by Shoxxo** [comment]
@Luzifix 

TC 6.x -> https://github.com/TrinityCore/TrinityCore

**Comment by Luzifix** [comment]
@Shoxxo ?

**Comment by AriDEV3** [comment]
Closed: https://github.com/ProjectSkyfire/SkyFire_548/commit/04e3e12444e83ff031e0b5c3983ad033d620fe37
