### ISSUE TITLE
Multiple Bugs (Talents, stances, stats)

### ISSUE THREAD

**Issue by Anddrw** [ProjectSkyfire/SkyFire_548#710]
Hi,

There is a problem related to most of the stances, to be more specific, when you activate a stance the aura doesn't apply or the correct bonus its not calculated.
Example: Monk (windwalker) tiger stance -> Cast roll spell -> Cannot move forward just backward.
- Talents:
1. When you learn new talents they are not applied or the skills are not working.
2. When you learn dual spec and activate the second spec, the skills are the same as on the first spec (should reset the old spec skills and apply the second specs skills).
3. When you logout the server does not save the talent related data.

**Comment by Anddrw** [comment]
How to reproduce:

1. Create a new monk character.
2. Activate the [Tiger Stance](http://www.wowhead.com/spell=103985/stance-of-the-fierce-tiger) 
3. Logout
4. Login

After the loading screen you will not be able to move forward or to jump correctly (the character stands in air as falling).

**Comment by SkyFire** [comment]
Will check this.

**Comment by Shoxxo** [comment]
Results? Or can be closed?
