### ISSUE TITLE
MacOsX wiki missing

### ISSUE THREAD

**Issue by zelin** [ProjectSkyfire/SkyFire_548#717]
I am sorry for making it an issue but its seriously required. A little wiki on how to setup will help a lot :)

**Comment by alterego21** [comment]
I don't own a mac. So I have never set on a mac. However you could setup a
Linux vm and run it from there.

**Comment by zelin** [comment]
Well i have a mac, if you can help me what to setup i can replicate it on mac most probably

**Comment by buraktutanlar** [comment]
Maybe this could be beneficial: http://wiki.projectskyfire.org/index.php?title=Installation_%28Linux_5xx%29

**Comment by Shoxxo** [comment]
Will be updated if we have users with an MacOS X

http://wiki.projectskyfire.org/index.php?title=Installation_(Mac_OS_X_5xx)
