### ISSUE TITLE
Russian name declension

### ISSUE THREAD

**Issue by Smerdokryl** [ProjectSkyfire/SkyFire_548#772]
**Description:**

When trying to use a russian character name, you cannot log in because of an error that roughly translates as 'Wrong name declension'. (I did enable all of those name-related settings in worldserver.conf, they don't help)

Note: it is possible to go around this problem by going to character_declinedname and manually creating a line for that character.

**Steps to reproduce the problem:**

1. Create a new character
2. Name him Владимир, or anything else in russian
3. Try to log in

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. 1873afc9205e 2018-01-01 16:24:54 -0600 (master branch) (Win64, Release) (worldserver-daemon)

**SFDB version:**  The current one

**Operating system:** Windows 10

P.S. I am uncertain whether this issue is somehow linked with [the previous one I submitted](https://github.com/ProjectSkyfire/SkyFire.548/issues/771). Playing on characters with english names and/or switching client language to english does not fix the latter.

**Comment by SkyFire** [comment]
It could be linked. I will need to find a clean Russian client to test this. I will get back to you on this issue.

**Comment by Smerdokryl** [comment]
If you do succeed in finding a clean Russian client, which is ~>HARD<~ to do, would you be so kind as to send me a link? I tried a lot but all I managed to find is either a god-forsaken torrent file, or a client provided by one of the 'big' russian servers, which seems to have already been altered by them. As far as I know, you have sensible reasons not to post any such links here, so I could give you my discord/email/whatever is convenient.
And thank you for looking into the issue

**Comment by Artamedes** [comment]
can try to do this
http://dist.blizzard.com.edgesuite.net/wow-pod-retail/NA/15890.direct/Data//ruRU/expansion1-speech-ruRU.MPQ
http://dist.blizzard.com.edgesuite.net/wow-pod-retail/NA/15890.direct/Data//ruRU/expansion2speech-ruRU.MPQ
http://dist.blizzard.com.edgesuite.net/wow-pod-retail/NA/15890.direct/Data//ruRU/expansion3-speech-ruRU.MPQ
http://dist.blizzard.com.edgesuite.net/wow-pod-retail/NA/15890.direct/Data//ruRU/expansion4-speech-ruRU.MPQ
etc
