### ISSUE TITLE
Shadow Bolt casting issue

### ISSUE THREAD

**Issue by kem008** [ProjectSkyfire/SkyFire_548#788]
Using SSL version: OpenSSL 1.0.2n  7 Dec 2017 (library: OpenSSL 1.0.2n  7 Dec 2017)
Using ACE version: 6.4.5
SkyFire 5.x.x rev. c259a3e8ceaa+ 2018-03-21 07:05:36 -0500 (master branch) (Win64, Release) (worldserver-daemon)
Realm running as realm ID 1
Using World DB: SFDB 548.Release.15
I am having issues with shadow bolt not casting right spell. It show casting Incinerate or just not casting it and mana cost of spells pretty weird. Any idea where I can fix it?

**Comment by Smerdokryl** [comment]
I am having the same issue

**Comment by LegionCaos** [comment]
those errors are in the core, 70% of spells have errors, you have to solve it with c ++,
I work in some, but I'm new and I do not know how to post it for the community

**Comment by AriDEV** [comment]
caused by warlock destruction passive
