### ISSUE TITLE
Ice Floes not working as intended

### ISSUE THREAD

**Issue by iamreyne** [ProjectSkyfire/SkyFire_548#797]
**Description:**

Ice Floes allows the player to cast while moving, however each spell cast does not use a charge. The player can cast unlimited spells while moving.

**Current behaviour:**

Cast Ice Floes. You can now cast as many spells while moving as possible until the effect expires.

**Expected behaviour:**

Cast Ice Floes. You can now cast one spell while moving until the effect expires, or the spell is cast.

**Steps to reproduce the problem:**

1. Spec into Ice Floes 
2. Cast Ice Floes
3. Cast anything else
4. Ice Floes is not removed when the cast is complete.

**SF rev. hash/commit:**  

5.x.x rev 6c707a4d746d 2018-06-01 13:20:44 +0200 (master branch) (Unix, Release)

**SFDB version:**  [SFDB 15](https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/)

**Operating system:** Ubuntu 14.06

**Comment by AriDEV** [comment]
Works as intended!
![grafik](https://user-images.githubusercontent.com/972273/72670200-40a10f80-3a3b-11ea-94c6-13c38d858f2e.png)
