### ISSUE TITLE
Water Elemental not working as intended

### ISSUE THREAD

**Issue by iamreyne** [ProjectSkyfire/SkyFire_548#799]
**Description:**

Water elemental does not cast Waterbolt without specifically telling it to each cast, with auto cast enabled. Additionally, the water elemental is unable to cast Freeze (the elemental makes the casting animation and sound, but does not cast)

**Current behaviour:**

Water elemental does not cast Waterbolt without specifically telling it to each cast, with auto cast enabled. Additionally, the water elemental is unable to cast Freeze (the elemental makes the casting animation and sound, but does not cast)

**Expected behaviour:**

With auto-cast enabled, the water elemental should spam Waterbolt. When the player tells the elemental to cast Freeze, the elemental should cast Freeze.

**Steps to reproduce the problem:**

1. Specialize in Frost
2. Summon Water Elemental
3. Set Waterbolt to auto-cast
4. Send Water Elemental to attack
5. Does not cast waterbolt.

**SF rev. hash/commit:**  

5.x.x rev 6c707a4d746d 2018-06-01 13:20:44 +0200 (master branch) (Unix, Release)

**SFDB version:**  [SFDB 15](https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/)

**Operating system:** Ubuntu 14.06

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire.548/commit/88494136a6387c1ad3cd15e8c5ff8f1f1f2a0585
