### ISSUE TITLE
Pyroblast not working as intended

### ISSUE THREAD

**Issue by iamreyne** [ProjectSkyfire/SkyFire_548#800]
**Description:**

Pyroblast does not give an instant-cast, no cost, damage buffed cast after landing two critical fire spells in a row.

**Current behaviour:**

After getting tow single-target direct damage Fire critical strike in a row, nothing happens.

**Expected behaviour:**

After getting two single-target direct damage Fire critical strike in a row, your next Pyroblast will be instant cast, cost no mana, and deal 25% additional damage. 

**Steps to reproduce the problem:**

1. Specialize in Fire
2. Land two direct damage, single target fire spells in a row.
3. Nothing happens.

**SF rev. hash/commit:**  

5.x.x rev 6c707a4d746d 2018-06-01 13:20:44 +0200 (master branch) (Unix, Release)

**SFDB version:**  [SFDB 15](https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/)

**Operating system:** Ubuntu 14.06

**Comment by GMKyle** [comment]
Please try:
DELETE FROM `spell_proc_event` WHERE `entry`= 44448;
INSERT INTO `spell_proc_event`(`entry`, `SchoolMask`, `SpellFamilyName`, `SpellFamilyMask0`, `SpellFamilyMask1`, `SpellFamilyMask2`, `SpellFamilyMask3`, `procFlags`, `procEx`, `ppmRate`, `CustomChance`, `Cooldown`) VALUES (44448,0,3,4194323,67112960,2097160,0,0,0,0,0,0);
DELETE FROM `spell_script_names` WHERE `spell_id` = 44448;
INSERT INTO `spell_script_names`(`spell_id`, `ScriptName`) VALUES (44448,'spell_mage_pyroblast_clearcasting');
In spell_mage.cpp
    SPELL_MAGE_HEATING_UP                        = 48107,
    SPELL_MAGE_HOT_STREAK                        = 48108
// Pyroblast Clearcasting Driver - 44448
class spell_mage_pyroblast_clearcasting : public SpellScriptLoader
{
public:
    spell_mage_pyroblast_clearcasting () : SpellScriptLoader("spell_mage_pyroblast_clearcasting") { }

    class spell_mage_pyroblast_clearcasting_AuraScript : public AuraScript
    {
        PrepareAuraScript(spell_mage_pyroblast_clearcasting_AuraScript);

        void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
        {
            Unit* caster = GetCaster();
            if (eventInfo.GetHitMask() & PROC_EX_CRITICAL_HIT)
            {
                if (!caster->HasAura(SPELL_MAGE_HEATING_UP))
                {    if (!caster->HasAura(SPELL_MAGE_HOT_STREAK))
                        caster->CastSpell(caster, SPELL_MAGE_HEATING_UP, true);
                }
                else
                {
                    caster->RemoveAurasDueToSpell(SPELL_MAGE_HEATING_UP);
                    caster->CastSpell(caster, SPELL_MAGE_HOT_STREAK, true);
                }
            }
            else if (caster->HasAura(SPELL_MAGE_HEATING_UP))
                caster->RemoveAurasDueToSpell(SPELL_MAGE_HEATING_UP);
        }

        void Register() override
        {
            OnEffectProc += AuraEffectProcFn(spell_mage_pyroblast_clearcasting_AuraScript::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        }
    };

    AuraScript* GetAuraScript() const override
    {
        return new spell_mage_pyroblast_clearcasting_AuraScript();
    }
};

new spell_mage_pyroblast_clearcasting();
