### ISSUE TITLE
Fists of Fury does not split damage evenly across all targets

### ISSUE THREAD

**Issue by iamreyne** [ProjectSkyfire/SkyFire_548#801]
**Description:**

Fists of Fury does not split damage evenly across all targets

**Current behaviour:**

When you cast Fists of Fury, it does the same damage to one target as it does to 5 targets.

**Expected behaviour:**

When you cast Fists of Fury, it should spread damage evenly across all targets in front of you.

**Steps to reproduce the problem:**

1. Specialize in Windwalker
2. Cast Fists of Fury on one target
3. Cast Fists of Fury on multiple targets
4. Does the same damage to each target regardless of number.

**SF rev. hash/commit:**  

5.x.x rev 6c707a4d746d 2018-06-01 13:20:44 +0200 (master branch) (Unix, Release)

**SFDB version:**  [SFDB 15](https://www.projectskyfire.org/index.php?/files/file/29-skyfire-548-database-release-15/)

**Operating system:** Ubuntu 14.06

**Comment by AriDEV** [comment]
Works as intended.
![grafik](https://user-images.githubusercontent.com/972273/72670115-01be8a00-3a3a-11ea-8a2d-d86ef1e0e67c.png)
In mists of pandaria damage was split accross targets, in WoD Patch 6.0.2 (2014-10-14) Fists of Fury got changed where it dealt full damage to primary target.
