### ISSUE TITLE
LFG

### ISSUE THREAD

**Issue by Nightprince** [ProjectSkyfire/SkyFire_548#821]
**Description:**

Dungeon Finder is not work . must rewrite packet
![wowscrnshot_080218_171533](https://user-images.githubusercontent.com/12217476/43584504-c786dd36-9677-11e8-8dc4-876c1697caaa.jpg)
![wowscrnshot_080218_171536](https://user-images.githubusercontent.com/12217476/43584505-c7eff42e-9677-11e8-9ac1-babd612f274d.jpg)
![wowscrnshot_080218_171537](https://user-images.githubusercontent.com/12217476/43584507-c839adee-9677-11e8-93c4-bf6df220d74f.jpg)

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. f1b78876fcb3+ 2018-07-26 10:10:15 +0200 (master branch) (Win32, Release)

**SFDB version:**  Release 17

**Operating system:** Win 10

**Comment by AriDEV** [comment]
The solo player packet isnt updated. 2and3 player groups should join the queue i guess?

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/commit/ade11833561318877d28ae33aa7896d27f483124

**Comment by AriDEV** [comment]
![image](https://user-images.githubusercontent.com/972273/46580494-e76bc300-ca25-11e8-8394-252648cd23a9.png)

**Comment by AriDEV** [comment]
Fixed since: https://github.com/ProjectSkyfire/SkyFire_548/commit/1b1b5c662674583a56f88450e6ceaf8248497b0c
