### ISSUE TITLE
Server Offline - Help

### ISSUE THREAD

**Issue by Winfinito** [ProjectSkyfire/SkyFire_548#835]
**Description:**

My server is offline

![screenshot_3](https://user-images.githubusercontent.com/43060750/45922090-cf763a00-be90-11e8-983b-2285bd02a310.png)

Using SSL version: OpenSSL 1.1.1  11 Sep 2018 (library: OpenSSL 1.1.0i  14 Aug 2018)
Using ACE version: 6.5.1
SkyFire 5.x.x rev. 10c0cd681f34+ 2018-08-29 10:13:03 +0200 (master branch) (Win64, Debug) (worldserver-daemon)

**SFDB version:**  Skyfire database 17

**Operating system:** Windows 10

**Comment by poserbiker** [comment]
That link to, i am assuming to a picture doesn't work

**Comment by SkyFire** [comment]
What is your client version?
Needs to be Build 18414

**Comment by Winfinito** [comment]
![screenshot_4](https://user-images.githubusercontent.com/43060750/45924129-ea16d600-bec5-11e8-812f-fc2d084a116f.png)
that's my version

**Comment by Artamedes** [comment]
you're trying to use 547 client, use 548

(547 is hexedited to display 548)

**Comment by Winfinito** [comment]
Thank you for your help. Finally I solved it. I downloaded the client again
