### ISSUE TITLE
Compilation in debian 9

### ISSUE THREAD

**Issue by pangolp** [ProjectSkyfire/SkyFire_548#846]
Good morning, sir. I know this is not the nomal format that would be used in a track, but I tried to compile the emulator in a debian 9 where I have other emulators, like azeroth-core and trinity-core. I couldn't compile it. I would be interested in contributing to the project, but as long as I can't have a server to test and fix, it's going to be really difficult for me. Anyway, I'm not an expert in C++, maybe I can collaborate a little with the topic of smart_scripts.

I don't know if the community has a discord or some other way to communicate.

Greetings and thanks in advance for any information.

**Comment by TheNeoTV** [comment]
Can you bring a Log or an error here to lets see what happend? I am working on a solution in the wiki for the latest Debian System.

**Comment by kncxstudio** [comment]
I have met same problem.Is this related to version of OpenSSL?

Logs:
In file included from /root/Disk/SkyFireEMU/src/server/shared/Cryptography/ARC4.cpp:20:0:
/root/Disk/SkyFireEMU/src/server/shared/Cryptography/ARC4.h:35:24: error: field ‘m_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
         EVP_CIPHER_CTX m_ctx;
                        ^~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /root/Disk/SkyFireEMU/src/server/shared/Cryptography/ARC4.h:24,
                 from /root/Disk/SkyFireEMU/src/server/shared/Cryptography/ARC4.cpp:20:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
src/server/shared/CMakeFiles/shared.dir/build.make:86: recipe for target 'src/server/shared/CMakeFiles/shared.dir/Cryptography/ARC4.cpp.o' failed
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/Cryptography/ARC4.cpp.o] Error 1
CMakeFiles/Makefile2:552: recipe for target 'src/server/shared/CMakeFiles/shared.dir/all' failed
make[1]: *** [src/server/shared/CMakeFiles/shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AriDEV** [comment]
yes its related to openssl what version of openssl you are using?

**Comment by pangolp** [comment]
Good afternoon, sir. You would have to redo the installation. I had basically followed the site guide, but as I had not been able to do so, I did not continue to try.

**Comment by TheNeoTV** [comment]
Try a test with the updated wiki Guide : https://wiki.projectskyfire.org/index.php?title=Installation_(Linux_5xx)

If you have some issues again, please tell me and i will recheck with the wiki. But should work.

**Comment by AriDEV** [comment]
just install latest openssl 1.1.1 instead of 1.0.2 and it should solve the issue above.

**Comment by kncxstudio** [comment]
Another cmake error:
CMake Error at cmake/macros/FindReadline.cmake:26 (MESSAGE):
  ** Readline library not found!

  **
Call Stack (most recent call first):
  CMakeLists.txt:75 (find_package)

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548#requirements
