### ISSUE TITLE
Wild Mushroom (Druid Spell) Server Crash

### ISSUE THREAD

**Issue by StormCW** [ProjectSkyfire/SkyFire_548#848]
'Wild Mushroom' spell causes the server to crash every time it's used.
Spell ID: 145205
Class: Druid
Spec: All
error screenshot:
![Screenshot_154](https://user-images.githubusercontent.com/50452507/58387174-eb774000-800a-11e9-8312-02230b5e511c.png)

**Comment by SkyFire** [comment]
Compile in debug and paste the out on a pastebin.

**Comment by StormCW** [comment]
Thank you for the fix.
