### ISSUE TITLE
Error C2440=:  impossible to convert  "bool *" в "my_bool *"sharedC:\Users\ADMIN\Desktop\11\src\server\shared\Database\QueryResult.cpp82

### ISSUE THREAD

**Issue by gevorg911** [ProjectSkyfire/SkyFire_548#856]
ОшибкаC2440=: невозможно преобразовать "bool *" в "my_bool *"sharedC:\Users\ADMIN\Desktop\11\src\server\shared\Database\QueryResult.cpp82

**Comment by Artamedes** [comment]
MySQL = 8.0 (Windows / Linux)

**Comment by gevorg911** [comment]
mysql 8 no 32 bit

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548#requirements

**Comment by ReyDonovan** [comment]
> ОшибкаC2440=: невозможно преобразовать "bool *" в "my_bool *"sharedC:\Users\ADMIN\Desktop\11\src\server\shared\Database\QueryResult.cpp82

`
    - m_isNull = new bool[m_fieldCount];
    + my_bool* m_isNull = new my_bool[m_fieldCount];`
