### ISSUE TITLE
error database

### ISSUE THREAD

**Issue by gevorg911** [ProjectSkyfire/SkyFire_548#861]
![2019-06-25_12h50_14](https://user-images.githubusercontent.com/39030731/60084218-28d50780-9748-11e9-99ab-3361cf89cee1.png)

**Comment by gevorg911** [comment]
Query:
CREATE TABLE `phase_area` (
  `AreaId` int(10) unsigned NOT NULL,
  `PhaseId` int(10) unsigned NOT NULL,
  `Comment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AreaId`,`PhaseId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

Error occured at:2019-06-25 12:58:35
Line no.:3655
Error Code: 1273 - Unknown collation: 'utf8mb4_0900_ai_ci'

**Comment by AriDEV** [comment]
what version of mysql ? the collation utf8mb4_0900_ai_ci is mysql 8.0.1+

**Comment by gevorg911** [comment]
I use mysql 5.7, but where did sql and mysql come from? I can not fill the base for 32 bits. There is no mysql 8

**Comment by AriDEV** [comment]
What processor do you have ?

**Comment by gevorg911** [comment]
I have a good processor, I compiled other servers

**Comment by HBSNET** [comment]
SF needs to be compiled on 64b OS (Linux Ubuntu 18.04 LTS or Windows 10). 
MySQL 8.0.1+ is required!
For Linux use CMake 3.15 and you'll be ok.

**Comment by Nightprince** [comment]
> what version of mysql ? the collation utf8mb4_0900_ai_ci is mysql 8.0.1+

I do not know why you insist SkyFire only on 64 bits.
It runs well on 32 bits.
You can use if for manage my_bool for versions 5.7 and bool instead of version 8.
You can also put at least MSVC on 2015 update 1.

**Comment by AriDEV** [comment]
@Nightprince stop telling people your boloks that are not true.
