### ISSUE TITLE
I have the same problem on my debian 9. Can you tell us which exactly package missing?

### ISSUE THREAD

**Issue by ckjet** [ProjectSkyfire/SkyFire_548#868]
I have the same problem on my debian 9. Can you tell us which exactly package missing?

_Originally posted by @ckjet in https://github.com/ProjectSkyfire/SkyFire_548/issues/812#issuecomment-517999197_

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548#requirements

**Comment by ckjet** [comment]
I installed all requirements, can you tell which exactly missing?
