### ISSUE TITLE
I installed all requirements, can you tell which exactly missing?

### ISSUE THREAD

**Issue by ckjet** [ProjectSkyfire/SkyFire_548#869]
I installed all requirements, can you tell which exactly missing?

_Originally posted by @ckjet in https://github.com/ProjectSkyfire/SkyFire_548/issues/868#issuecomment-518041356_

**Comment by ckjet** [comment]
Can you don't close issue before we solve it? Thanks.

**Comment by AriDEV** [comment]
https://github.com/ProjectSkyfire/SkyFire_548/issues/856

**Comment by SkyFire** [comment]
PEBKAC "Problem Exists Between Keyboard And Chair"

**Comment by ckjet** [comment]
My gcc:
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 

Cmake:

$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

ACE: 6.5.6
Debian 9
Openssl: OpenSSL 1.1.1c  28 May 2019


In first, I get error as in issue. But now I get error:

/home/wow/wow-source/src/server/shared/Database/MySQLConnection.cpp:486:14: error: use of undeclared identifier
      'CR_INVALID_CONN_HANDLE'
        case CR_INVALID_CONN_HANDLE:
             ^
1 error generated.
make[2]: *** [src/server/shared/CMakeFiles/shared.dir/build.make:232: src/server/shared/CMakeFiles/shared.dir/Database/MySQLConnection.cpp.o] Ошибка 1

**Comment by DevPrimeR** [comment]
verify that the version of MySql installed is correct

**Comment by ckjet** [comment]
mysql  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by AriDEV** [comment]
use mysql 8 and not mariadb.
https://dev.mysql.com/downloads/repo/apt/

the issue you have is mariadb related. maybe open ticket at mariadb.
