### ISSUE TITLE
Consultation on discord

### ISSUE THREAD

**Issue by pangolp** [ProjectSkyfire/SkyFire_548#870]
Good evening, sorry to bother you. I know it's not the place where I might have to ask these kinds of questions, but I'd like to see if I can contribute to the project.

The only thing I wanted to know is if they use discord and where I can find it, to join and maybe debate or make a query about the arrangements to be made and some other issue that may arise.

I'm not an expert in C++, for the moment more than anything I do scripts in sql mainly for version 3.3.5 and some for version 4.3.4.

Thanks in advance for any information.

**Comment by poserbiker** [comment]
https://discord.gg/pdA62d

**Comment by pangolp** [comment]
Thank you very much.
