### ISSUE TITLE
Shop Unavailable

### ISSUE THREAD

**Issue by Nightprince** [ProjectSkyfire/SkyFire_548#871]
**Description:**

Shop is not work. need to write code, opcode and handler.

**Current behaviour:**

- [ ] Code, opcode and handler
- [ ] Add category
- [ ] Add items
- [ ] Buy item
- [ ] Commands

![image](https://www.yekta-upload.ir/uploads/03070d9ad56f1.png)

**Expected behaviour:**

![image](https://www.yekta-upload.ir/uploads/b13f577948f91.jpg)

**Comment by SkyFire** [comment]
This will not be implemented any time in the near future. No reason to have this.

**Comment by Nightprince** [comment]
> This will not be implemented any time in the near future. No reason to have this.

But this is part of the game and its features. What's the difference between Change Faction and other game services though?

**Comment by AriDEV** [comment]
It's a misc system.
it's not required in the near future and has no priority.

**Comment by LichKing255** [comment]
This is good system. i need too.

**Comment by TheNeoTV** [comment]
No, then 100 server will open and more shit no needed donor shit comes. Any request of Shop Implementation will be closed immediently. If you need it, learn codsing and do yourself. We will not implement it in any time this project existing.
