### ISSUE TITLE
Loading Transport Templates Crash

### ISSUE THREAD

**Issue by TheGhostGroup** [ProjectSkyfire/SkyFire_548#872]
**Description:**
World server crashes Loading Transport Templates

**Current behaviour:**
Loading Transport Templates...

/home/server/github/skyfire.548/src/server/game/Maps/TransportMgr.cpp:133 in GeneratePath ASSERTION FAILED:
  !keyFrames.empty()
./worldserver(+0x7cbdd6) [0x564758763dd6]
./worldserver(+0x917a2f) [0x5647588afa2f]
./worldserver(+0x3b5923) [0x56475834d923]
./worldserver(+0x38a00a) [0x56475832200a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fb3ee539b6b]
./worldserver(+0x39ecfa) [0x564758336cfa]

**Expected behaviour:**

None

**Steps to reproduce the problem:**

Compiled Skyfire using latest commit. 44e911e63076

Launched world server and then crash at loading transport templates.

**SF rev. hash/commit:** 
SkyFire 5.x.x rev. 44e911e63076 2019-08-16 20:04:09 +0200 (master branch) (Unix, Release) (worldserver-daemon)

**SFDB version:** 
SFDB 548.Release.19.5

**Operating systems:** 
Ubuntu Server 19.04 x64
Debian 10 x64

**Comment by SkyFire** [comment]
We would need to have you compile in debug and post a crashlog on pastebin. I can't reproduce your error.

**Comment by TheGhostGroup** [comment]
Hi,
sorry it took so long as i have had health problems that have made things hard.

Here https://pastebin.com/4qLRmfa9 is the crash log from a compile i did on windows as a test. Same problem.

**Comment by AriDEV** [comment]
did you added any custom transports to the database?
