### ISSUE TITLE
Sign up in skyfire webiste

### ISSUE THREAD

**Issue by alwayswowfan** [ProjectSkyfire/SkyFire_548#873]
**Description:**

hello,when i was sign up in "skyfire" website,and creat the account need the person to pass the Security Check,the Security Check have two question:
1.What is the current supported build for SkyFire
2.what year was skyfire established? Answer in GitHub Repository
and also,i have known that the question,but i dont know the keyword.

could somebody tell me that what the keyword is?thank you so much!

**Comment by SkyFire** [comment]
https://github.com/ProjectSkyfire/SkyFire_548
It's not rocket science. Seek and you shall find.

**Comment by alwayswowfan** [comment]
> https://github.com/ProjectSkyfire/SkyFire_548
> It's not rocket science. Seek and you shall find.

Hello bro,im badly in English that i have tried when i input "2011"or"in 2011","established in 2011"....
Its still not work.i just wanna download the db of the mop...
thank you so much for your reply.

**Comment by alwayswowfan** [comment]
> > https://github.com/ProjectSkyfire/SkyFire_548
> > It's not rocket science. Seek and you shall find.
> 
> Hello bro,im badly in English that i have tried when i input "2011"or"in 2011","established in 2011"....
> Its still not work.i just wanna download the db of the mop...
> thank you so much for your reply.

ok,sure.i have successfully registered.
I find that my computer donesnt receive the captcha.So i used vpn,them i passed the verification.
thanks.
