### ISSUE TITLE
error compilation

### ISSUE THREAD

**Issue by JadeCore** [ProjectSkyfire/SkyFire_548#875]
104 error 
![2019-09-21_05h23_41](https://user-images.githubusercontent.com/39030731/65366053-1af02f00-dc30-11e9-8b3c-6eae83922f8c.png)
![2019-09-21_05h22_59](https://user-images.githubusercontent.com/39030731/65366056-1e83b600-dc30-11e9-971a-d0138de1de76.png)

windows 7   64 bit  mysql 8

**Comment by SkyFire** [comment]
MySQL = 8.0 (Windows / Linux)
CMake = 3.13.1/3.5.1 (Windows / Linux)
OpenSSL = 1.1.1/1.1.0G (Windows / Linux)
GCC = 8.1.0 (Linux only)
MS Visual Studio = 16 (2019) (Windows only)
