### ISSUE TITLE
database world

### ISSUE THREAD

**Issue by JadeCore** [ProjectSkyfire/SkyFire_548#876]
are you using a mariadb database download?

**Comment by JadeCore** [comment]
how to make mysql 5.6 + openSLL 1.0.2+ MS Visual Studiovs 2015, so it was easier for me???

**Comment by SkyFire** [comment]
MySQL = 8.0 (Windows / Linux)
CMake = 3.13.1/3.5.1 (Windows / Linux)
OpenSSL = 1.1.1/1.1.0G (Windows / Linux)
GCC = 8.1.0 (Linux only)
MS Visual Studio = 16 (2019) (Windows only)
is only supported.
