### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by Mistixsnet** [ProjectSkyfire/SkyFire_548#885]
Hi, I am a Private Project Developer of Mists of Pandaria and Legion. I have one of the Best Realms of Pandaria at 98%. I can Help You Here in Your Project If You Can Demand Access to Discord and Invitation to the Source to Help You in Development

**Comment by Mistixsnet** [comment]
My Discord https://discord.gg/RUmg9pF

**Comment by SkyFire** [comment]
It's an open community. What you choose to share helps everyone. Just for the repository and you can make a pull request per our guidelines.
