### ISSUE TITLE
Compiling on windows

### ISSUE THREAD

**Issue by Dokman** [ProjectSkyfire/SkyFire_548#886]
**Description:**
QueryResult.cpp
Line 82:  m_rBind[i].is_null = &m_isNull[i];
can't make a conversion from my_Bool* to Bool*

**Current behaviour:**

![image](https://user-images.githubusercontent.com/2290904/75024338-85d0bb00-5499-11ea-9444-8f748abca61a.png)

**Expected behaviour:**

Compile the software

**SF rev. hash/commit:** 
https://github.com/ProjectSkyfire/SkyFire_548/commit/bfe42e0ba7420ca04dc24959f9a2ab36b6db6500

**Operating system:** Win10

**Comment by AriDEV** [comment]
skyfire requires mysql 8, read requirements section
