### ISSUE TITLE
pandarian scripts!

### ISSUE THREAD

**Issue by warcrafte** [ProjectSkyfire/SkyFire_548#898]
Where is it pandarian scripts? not on the source?!

SkyFire.548/tree/master/src/server/scripts/Pandaria

 !! ?? !!

**Comment by AriDEV** [comment]
Loremaster cho decided to hide those Ancient Hieroglyphs from the mogu.

**Comment by warcrafte** [comment]
panda on the skyfire don't work?

**Comment by AriDEV** [comment]
I have heard they are good cooks.

**Comment by warcrafte** [comment]
Where can I find a good project for Panda?

**Comment by AriDEV** [comment]
WWF project is good project for Pandas.

**Comment by warcrafte** [comment]
link ?

**Comment by AriDEV** [comment]
https://wwf.panda.org/

**Comment by DerEnderman** [comment]
Kiddin me? Issue report now for advertising. Ari du Spack was ist los mit dir, was kickst du mich?

**Comment by DerEnderman** [comment]
Ari du Spack was is los mit dir?

**Comment by SkyFire** [comment]
Du musst kein Arschloch sein. Es ist Aprilscherz.

**Comment by warcrafte** [comment]
stfu
