### ISSUE TITLE
Compile error ubuntu 18.04lts

### ISSUE THREAD

**Issue by redbaron99** [ProjectSkyfire/SkyFire_548#903]
/root/SkyFire.548/src/server/shared/Database/QueryResult.cpp: In constructor ‘PreparedResultSet::PreparedResultSet(MYSQL_STMT*, MYSQL_RES*, uint64, uint32)’:
/root/SkyFire.548/src/server/shared/Database/QueryResult.cpp:82:30: error: cannot convert ‘bool*’ to ‘my_bool*’ {aka ‘char*’} in assignment
   82 |         m_rBind[i].is_null = &m_isNull[i];
      |                              ^~~~~~~~~~~~
      |                              |
      |                              bool*
i used https://wiki.projectskyfire.org/index.php?title=Installation_(Ubuntu_18.04_LTS) guid. 
i have mysql 8.0, and gcc g++ 9 why?

**Comment by GrenderG** [comment]
That was happening to me too, now I switched to Ubuntu 20.04 and using `mysql  Ver 15.1 Distrib 10.3.22-MariaDB` works fine. :+1:
