### ISSUE TITLE
BUG IN TWO MOUNT´S

### ISSUE THREAD

**Issue by merdlin** [ProjectSkyfire/SkyFire_548#904]
**BUG IN TWO MOUNT´S**

CHANGEME Description of the problem or issue here.

**There is no spell or anything.**

**what should happen is there is a spell and be learned after clicking on the item.**

**Steps to reproduce the problem:**

1. .additem 112326
2. .additem 112327
3. Try to learn the two mounts.

**SF rev. hash/commit:** 

[MASTER](https://github.com/ProjectSkyfire/SkyFire_548/commit/61490cedefd0aa8f77c075ccc6ae8f752a995b67)

**SFDB version:**  the most up-to-date.

**Operating system:** windows server 2016

**Comment by AriDEV** [comment]
This 2 Mounts were Added in patch 6.0.1.18297 which is the 3rd closed alpha build of the next comming expansion Warlords of Draenor. Thats why they cant be found in 5.4.8.18291 or 5.4.8.18414.
