### ISSUE TITLE
[SPELL/ROGUE/SUBTLETY] Hemorrhage

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#936]
This issue is related to #1005

**Current behaviour:**

[Hemorrhage](https://mop-shoot.tauri.hu/?spell=16511) casts Sinister Strike.

**Expected behaviour:**

Should cast Hemorrhage.

**Steps to reproduce the problem:**

1. Make a rogue, 
2. Spec into Subtlety > cast Hemorrhage > check combat log > see that it casts Sinister Strike

**SF rev. hash/commit:** 

Skyfire rev. 7f1a4abd1b9f+

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
closed in: https://github.com/ProjectSkyfire/SkyFire_548/commit/e4c0960c549888d3657b258a352535bc9833a42d
