### ISSUE TITLE
[SPELL/ROGUE/ASSASSINATION] Dispatch

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#958]
This issue is related to #1005

**Current behaviour:**

[Dispatch](https://mop-shoot.tauri.hu/?spell=111240) casts Sinister Strike.

**Expected behaviour:**

Should use Dispatch.

**Steps to reproduce the problem:**

1. Make a rogue
2. Spec into Assassination > Cast Dispatch > see in combat log that it casts Sinister Strike

**SF rev. hash/commit:** 

Skyfire rev. 164451ca0b0b

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
closed in: https://github.com/ProjectSkyfire/SkyFire_548/commit/e4c0960c549888d3657b258a352535bc9833a42d
