### ISSUE TITLE
[SPELL/ROGUE/ASSASSINATION] Envenom

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#959]
**Current behaviour:**

[Envenom](https://mop-shoot.tauri.hu/?spell=32645) partially works. It does damage, but does not give the buff.

**Expected behaviour:**

Envenom should also give a buff that increases your chance of poisons application by 15% for 1 seconds + 1 seconds pr combo point.

**Steps to reproduce the problem:**

1. Make a rogue
2. Spec into Assassination > Stack combo points > Use Envenom > see that you don't get the Envenom buff

**SF rev. hash/commit:** 

Skyfire rev. 164451ca0b0b

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
closed in: https://github.com/ProjectSkyfire/SkyFire_548/commit/e4c0960c549888d3657b258a352535bc9833a42d
