### ISSUE TITLE
[SPELL/ROGUE/ASSASSINATION] Mutilate

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#961]
**Current behaviour:**

[Mutilate](https://mop-shoot.tauri.hu/?spell=1329) generates 4 combo points.

**Expected behaviour:**

Mutilate should generate 2 combo points.

Mutilate is combined by Mutilate and Mutilate Off-Hand, so I suspect them each to reward 2 combo points.

![image](https://user-images.githubusercontent.com/62337627/93521207-02445300-f930-11ea-872b-7a7ce21c5f55.png)

**Steps to reproduce the problem:**

1. Make a rogue
2. Spec into Assassination > cast Mutilate > see that it generates 4 combo points.

**SF rev. hash/commit:** 

Skyfire rev. 164451ca0b0b

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by lingxDEV** [comment]
Follow up:

Casting Mutilate consist of casting 3 spells.

The one you press: [Mutilate](https://mop-shoot.tauri.hu/?spell=1329) (1329)
- Trigger 1: [Mutilate](https://mop-shoot.tauri.hu/?spell=5374)
- Trigger 2: [Mutilate Off-Hand](https://mop-shoot.tauri.hu/?spell=27576)

Right now Trigger 1 and Trigger 2 are both generating 1 combo point for some reason. They should not.
The main spell, the one you press, generates 2 combo points as it should.

To fix the bug, remove whatever is causing Trigger 1 & 2 to each generate 1 combo point.

**Comment by Crypticaz** [comment]
Issue still persists after https://github.com/ProjectSkyfire/SkyFire_548/commit/0e61f8a904c9df2357a6b4812c02ea96a7be1969 fix and most recent commit https://github.com/ProjectSkyfire/SkyFire_548/commit/5dc77ecdb8fbb3be3a736d6bec24e4527e947d73
