### ISSUE TITLE
[SPELL/ROGUE/ASSASSINATION] Vendetta

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#962]
**Current behaviour:**

[Vendetta](https://mop-shoot.tauri.hu/?spell=79140) spell itself is working, but there's a minor bug. If Vendetta is cast on another rogue and that rogue vanishes, Vendetta will wear off.

**Expected behaviour:**

Vendetta should persist when the target uses Vanish.

**Steps to reproduce the problem:**

1. Make a rogue (account 1)
2. Make a another rogue (account 2)
3. On rogue 1 cast Vendetta on rogue 2 > Cast Vanish on rogue 2 > see that the Vendetta debuff disappears instantly.

**SF rev. hash/commit:** 

Skyfire rev. 164451ca0b0b

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
![grafik](https://user-images.githubusercontent.com/972273/93526171-5b63b500-f937-11ea-966f-9e5fca6bac16.png)
