### ISSUE TITLE
[SPELL/MAGE] Conjure Refreshment Table

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#978]
**Current behaviour:**

[Conjure Refreshment Table](https://mop-shoot.tauri.hu/?spell=43987) does not work.

**Expected behaviour:**

Should spawn a table you can click and get conjured refreshments from (read tooltip)

**Steps to reproduce the problem:**

1. Make a Mage
2. Cast Conjure Refreshment Table > see that nothing happens

**SF rev. hash/commit:** 

Skyfire rev. 164451ca0b0b

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
closed in: https://github.com/ProjectSkyfire/SkyFire_548/commit/85acb0850be833fb6f6ad5e6223696d027c5e075
