### ISSUE TITLE
[SPELL/WARRIOR] Armor Skills

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#991]
**Current behaviour:**

Reference spell: [Armor Skills](https://mop-shoot.tauri.hu/?spell=76268)

You can't equip plate gear as warrior.

**Expected behaviour:**

After reaching level 40, you should be able to equip plate armor.

Note that visually you don't lose any rage, but behind the scenes all your rage is gone. 

**Steps to reproduce the problem:**

1. Make a warrior
2. Set level to 40 > try to equip a plate armor piece > see that you can't equip it.

**SF rev. hash/commit:** 

Skyfire rev. 0e61f8a904c9

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by AriDEV** [comment]
no, in pandaria this is the only thing you still learn at trainers. paladins and warriors learn plate armor from trainers at level 40 still.

**Comment by lingxDEV** [comment]
I've spent a long time researching this. It's hard to find any patch notes talking about this.

After a long time I managed to find a guy who uploaded his leveling from 1-90 as a warrior in MoP. I scouted the videos to find some evidence that would make it clear that you do NOT have to train these armor skills at a trainer in Mist of Pandaria.

**Evidence:**

Our young Keilar reaches level 38 ([here](https://youtu.be/BTAYGGUyFjs?t=226)). A few videos later, he finally visits a vendor and hover some items in his bag. At this point Keilar is level 38 and so when he hovers a plate item, it shows in red ([here](https://youtu.be/2aYC1gU1JQs?t=124)) because he is unable to equip it.

Fast forward a few videos and Keilar reaches level 40 ([here](https://youtu.be/Mys0pjTrWLc?t=343)). As you can see by the end of the video, it says "Feature Unlocked! Plate Mail".

Fast forward just a little bit more, in the same dungeon, Keilar hovers a plate item again. This time the "Plate" tag shows in white, because now he can equip it ([here](https://youtu.be/5uV1Y2HHIEI?t=113) - pause the video immidiately).

Fast forward a few videos and Keilar FINALLY realize he has had plate shoulders laying in his bags the whole time and he FINALLY equips them (made me watch 10 vidoes god damnit). He equips the Plate shoulders and he NEVER visited a trainer to train Plate Mail specilization. Watch him equip ([here](https://youtu.be/qQzhinzHn1s?t=83)).


All the videos are on his channel going from 1-90, more than 1200 videos, everything is included. 

He reaches level 40 in Pt 187 and equips the plate shoulders in Pt 198. He never visits a trainer in between.

This is probably the most time I've ever spent researching for something. Please treat it good.

**Comment by JakobJR** [comment]
Further more when Keilar reaches level 40, notice what happens in his window on the right. The video is super low quality, but it states that he is now able to use plate:
![image](https://user-images.githubusercontent.com/12740333/93886709-0f719100-fce6-11ea-91b7-562115c184ad.png)

This is what it says:
![image](https://user-images.githubusercontent.com/12740333/93886782-20ba9d80-fce6-11ea-95f3-563f122f473d.png)

**Comment by lingxDEV** [comment]
Further more when Keilar reaches level 40, notice what happens in his window on the right. The video is super low quality, but it states that he is now able to use plate:
![xx](https://user-images.githubusercontent.com/12740333/93887101-8d359c80-fce6-11ea-81cc-bdb32100928a.jpg)


This is what it says:
![image](https://user-images.githubusercontent.com/12740333/93886782-20ba9d80-fce6-11ea-95f3-563f122f473d.png)

**Comment by lingxDEV** [comment]
Found another example. This is a paladin, using RaF to boost his low level character. Notice when he hits level 40, he gets the same gossip in chat:
https://youtu.be/zqNHLwFUsaE?t=184

**Comment by lingxDEV** [comment]
From 5.0.4 patch notes:
![image](https://user-images.githubusercontent.com/62337627/93892065-67ab9180-fcec-11ea-8457-1c8a5fc306cd.png)


I'll stop researching now, lol. Think I've made my point.
