### ISSUE TITLE
[SPELL/WARRIOR] Enrage

### ISSUE THREAD

**Issue by lingxDEV** [ProjectSkyfire/SkyFire_548#993]
**Current behaviour:**

Enrage procs when using any damaging ability 100% of the times.

**Expected behaviour:**

Enrage should only proc from Mortal Strike, Bloodthirst, Colossus Smash, Devastate and Shield Slam AND ONLY if they're critical strikes.

Enrage should also proc when Blocking a critical strike.

**Steps to reproduce the problem:**

1. Make a warrior
2. Use any damaging ability > See that you get the Enrage buff

**SF rev. hash/commit:** 

Skyfire rev. 0e61f8a904c9

**SFDB version:**  

stable5

**Operating system:** 

win10 64

**Comment by fulayfel** [comment]
Also worth adding that In Protection spec, whenever you take damage from an NPC you also proc [Enrage](https://mop-shoot.tauri.hu/?spell=12880)
