### ISSUE TITLE
[QUEST PANDAREN] huojin trainee

### ISSUE THREAD

**Issue by darkmoi31** [ProjectSkyfire/SkyFire_548#998]
**Description:**

can't fight with huojin trainee or tushui trainee

**Current behaviour:**

can't fight
**Expected behaviour:**

fight with dialog
**Steps to reproduce the problem:**

1. take quest pandaren "The lesson of stifled pride (id : 29524)
2. try speak huojin trainee or tushui trainee

**SF rev. hash/commit:** 

SkyFire 5.x.x rev. b17e57ee2e1b 2020-09-23 01:13:06 +0200 (master branch) (Unix, Release)

**SFDB version:**  SFDB 548.Release.20.03

**Operating system:** Ubuntu 18.04 server

**Comment by victhorinox** [comment]
i have this same problem.

**Comment by jesuisuncitron9** [comment]
Hi @darkmoi31 !

I don't know if you have resolve your problem but if other people get this issue :

You can retrieve the guid of "Tushui Trainee" with this query :

`SELECT * FROM world.quest_objective WHERE description LIKE "%Trainee%";`

-> 254896

Now put this query : 

`SELECT * FROM world.creature_template where entry = "254896";`

It will give you an entry return and you can modify faction_A / faction_H  (35 if you want attack them) column for make Tushui Trainee "neutral" (you can attack them or just ignore without aggro)

It's not the correct way for solve this problem and it's pretty ugly, i don't have many experience about Wow Emulation but i think that you need to create a gossip_menu and link them with creature_template entry for Tushui Trainee. (+ add the smart_scripts entry in db too)
